language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - "pip install -e ."
  - "pip install -r requirements-dev.txt"
script:
  - py.test --cov celery_once --cov-report term-missing
after_success:
  - coveralls
